<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-12-13T14:21:00+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'en_GB',
    'version_installed' => '8.0.1',
    'version_db_installed' => '20161203000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1481634581,
        'do_page_reindex_check' => false,
    ],
    'accessibility' => [
        'toolbar_titles' => true,
        'toolbar_large_font' => false,
        'display_help_system' => true,
    ],
];
