<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-12-09T20:21:40+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'en_GB',
    'version_installed' => '8.0.1',
    'version_db_installed' => '20161203000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1481272608,
        'do_page_reindex_check' => false,
        'latest_version' => '8.0.1',
    ],
    'accessibility' => [
        'toolbar_titles' => true,
        'toolbar_large_font' => false,
        'display_help_system' => true,
    ],
    'user' => [
        'registration' => [
            'email_registration' => true,
            'type' => 'disabled',
            'captcha' => false,
            'enabled' => false,
            'notification' => false,
        ],
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
];
