<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-12-14T15:03:08+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'en_GB',
    'version_installed' => '8.0.1',
    'version_db_installed' => '20161203000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1481634581,
        'do_page_reindex_check' => false,
    ],
    'accessibility' => [
        'toolbar_titles' => true,
        'toolbar_large_font' => false,
        'display_help_system' => true,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
