<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-12-13T14:09:02+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Sparrowtail',
        ],
    ],
];
