<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-12-09T20:17:45+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.seo.canonical_ssl_url
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Sparrowtail',
            'seo' => [
                'canonical_url' => '',
                'canonical_ssl_url' => '',
            ],
        ],
    ],
];
